site_name: maestro
site_description: A minimal post-training library.
site_url: https://rosikand.github.io/maestro/
repo_url: https://github.com/rosikand/maestro
repo_name: rosikand/maestro

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - content.code.copy

nav:
  - Home: index.md
  - Tasks: tasks.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            docstring_options:
              returns_named_value: false
            show_source: true
            show_root_heading: true
            members_order: source

markdown_extensions:
  - admonition
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
